// GENERATED BY MITOSIS

import { Fragment, component$, h, useScopedStyles$ } from "@builder.io/qwik";
export const ItemList = component$((props) => {
  useScopedStyles$(STYLES);
  return (
    <ul class="shadow-md rounded">
      {(props.list || []).map((item) => {
        return <li class="border-gray-200 border-b li">{item}</li>;
      })}
    </ul>
  );
});
export default ItemList;
export const STYLES = `.li { 
padding: 10px; }`;
