// GENERATED BY MITOSIS

import ItemList from "./item-list";
import {
  Fragment,
  component$,
  h,
  useScopedStyles$,
  useStore,
} from "@builder.io/qwik";
export const setItemName = function setItemName(props, state, event) {
  state.newItemName = event.target.value;
};
export const addItem = function addItem(props, state) {
  state.list = [...state.list, state.newItemName];
};
export const MyComponent = component$((props) => {
  useScopedStyles$(STYLES);
  const state = useStore({ list: ["hello", "world"], newItemName: "New item" });
  return (
    <div class="div">
      <link
        href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
        rel="stylesheet"
      ></link>
      <input
        class="shadow-md rounded w-full px-4 py-2"
        value={state.newItemName}
        onChange$={(event) => setItemName(props, state, event)}
      ></input>
      <button
        class="bg-blue-500 rounded w-full text-white font-bold py-2 px-4 button"
        onClick$={() => addItem(props, state)}
      >
        Add list item
      </button>
      <ItemList list={state.list}></ItemList>
    </div>
  );
});
export default MyComponent;
export const STYLES = `.div { 
padding: 10px; }.button { 
margin: 10px 0; }`;
